name: CMake

on: [push]

env:
  # 2021, Shishkov M.: Currently only this build type is hardcoded in the build.sh file
  BUILD_TYPE: Release
  WORKING-DIR: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{env.WORKING-DIR}}
      shell: bash
      run: |
          ls -R | build.sh
